version: '3.7'
services:


  #Balancer
  reverse_proxy:
    image: cwmts-docker.artifactory.prostream.ru/images/backend/reverse-proxy:local
    restart: always
    ports:
      - "80:80"
    container_name: cwmts_reverse_proxy
    network_mode: host
  #Backend
  backend_webserver:
    image: ${BACKEND_WEBSERVER_IMAGE}
    container_name: cwmts_backend_webserver
    restart: always
    ports:
      - "8080:8080"
  backend_app:
    image: ${BACKEND_APP_IMAGE}
    container_name: cwmts_backend_app
    env_file:
      - .env
  #Redis
  redis:
    image: redis:5-alpine
    ports:
      - '6379:6379'
    container_name: cwmts_redis


  #MySQL Service
  db:
    image: mysql:8.0.12
    container_name: cwmts_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - type: volume
        source: frontend_db_data_local
        target: /var/lib/mysql/

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
#Volumes
volumes:
  frontend_db_data_local:

