export enum ZIndexes {
  ROADS = 1,
  CARS = 2,
  DECORATION = 3,
  BUILDING_ONE_LEVEL = 10,
  BUILDING_TWO_LEVEL = 11,
  BUILDING_THREE_LEVEL = 12,
  BUILDING_FOUR_LEVEL = 13,
  UI_BUTTON = 20,
  TUTORIAL = 25,
  MODAL = 30,
  ERROR = 40,
}
